In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
cd ..

/home/wbaik/Code/data_science/temp_folder


In [3]:
fundamental_data = pd.read_csv('10K_data.csv')
price_data = pd.read_csv('./fundamental_data/price_data')

In [4]:
from dateutil import parser
price_data.index = price_data['date'].apply(parser.parse)

In [5]:
to_drop_for_insufficient_data = [ticker for ticker in price_data if len(price_data[ticker][price_data[ticker].isnull()]) > 250]

[price_data.drop(ticker, axis=1, inplace=True) for ticker in to_drop_for_insufficient_data]

[None, None, None, None, None, None]

In [6]:
fundamental_data.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'Symbol', 'Wikipedia Link', 'Name',
       'Sector', 'SEC Filings Link', 'CIK', 'Enterprise Value', 'Trailing P/E',
       'Enterprise Value/Revenue', 'Enterprise Value/EBITDA', 'Revenue',
       'EBITDA', 'Diluted EPS', 'Market Cap (intraday)', 'Forward P/E', 'Beta',
       '50-Day Moving Average', '200-Day Moving Average', 'Avg Vol (3 month)',
       'Avg Vol (10 day)', 'Shares Outstanding'],
      dtype='object')

In [7]:
columns = fundamental_data.columns
columns = [col for col in columns]

for col in columns[6:8]:
    fundamental_data = fundamental_data.drop(col, axis=1)
    
for col in columns[-5:]:
    fundamental_data = fundamental_data.drop(col, axis=1)

# should be inplace but ...
fundamental_data = fundamental_data.drop('Wikipedia Link', axis=1)
fundamental_data = fundamental_data.drop('Diluted EPS', axis=1)
fundamental_data = fundamental_data.drop('Beta', axis=1)

In [8]:
fundamental_data = fundamental_data.drop(['Enterprise Value/Revenue', 'Enterprise Value/EBITDA'], axis=1)

In [9]:
fundamental_data.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'Symbol', 'Name', 'Sector',
       'Enterprise Value', 'Trailing P/E', 'Revenue', 'EBITDA',
       'Market Cap (intraday)', 'Forward P/E'],
      dtype='object')

In [10]:
fundamental_data.iloc[:,3:].head()

Name                  Sector  Enterprise Value  \
0           3M Company             Industrials      1.427800e+11   
1  Abbott Laboratories             Health Care      1.247200e+11   
2          AbbVie Inc.             Health Care      1.833600e+11   
3        Accenture plc  Information Technology      9.679000e+10   
4  Activision Blizzard  Information Technology      5.254000e+10   

   Trailing P/E       Revenue        EBITDA  Market Cap (intraday)  \
0         26.77  3.166000e+10  8.880000e+09           1.262300e+11   
1        214.01  2.739000e+10  5.960000e+09           1.005400e+11   
2         27.21  2.822000e+10  1.214000e+10           1.424500e+11   
3         26.12  3.586000e+10  5.850000e+09           9.478000e+10   
4        179.33  7.020000e+09  2.230000e+09           4.898000e+10   

   Forward P/E  
0        18.50  
1        17.88  
2        10.28  
3        20.13  
4        21.52

In [11]:
by_sectors = fundamental_data.groupby('Sector').agg([np.mean, np.std]).iloc[:,4:]

In [12]:
by_sectors

Enterprise Value               Trailing P/E  \
                                       mean           std         mean   
Sector                                                                   
Consumer Discretionary         5.138887e+10  1.009863e+11    24.680423   
Consumer Staples               7.046485e+10  7.034629e+10    25.122727   
Energy                         5.428429e+10  8.526935e+10    27.240952   
Financials                     2.847176e+10  2.384247e+10    19.031176   
Health Care                    6.034564e+10  6.625571e+10    68.369091   
Industrials                    4.075159e+10  3.962559e+10    29.237778   
Information Technology         9.593136e+10  1.705597e+11    65.158305   
Materials                      3.301348e+10  3.313349e+10    29.447391   
Real Estate                    2.697576e+10  1.692227e+10    51.707576   
Telecommunication Services     2.316200e+11  1.543733e+11     7.240000   
Utilities                      4.393750e+10  2.854201e+10    26.672500   

                                             Revenue                \
                                   std          mean           std   
Sector                                                               
Consumer Discretionary       29.115662  2.262944e+10  3.117771e+10   
Consumer Staples             24.461588  4.992667e+10  9.231636e+10   
Energy                       30.598941  3.547238e+10  5.890587e+10   
Financials                   10.816313  2.069441e+10  4.147093e+10   
Health Care                 117.825699  3.099582e+10  4.692515e+10   
Industrials                  28.889305  1.831175e+10  1.861421e+10   
Information Technology      103.114993  1.968780e+10  3.681394e+10   
Materials                    37.064463  1.339000e+10  1.314028e+10   
Real Estate                  40.846119  2.963997e+09  2.658934e+09   
Telecommunication Services    0.701498  1.014133e+11  7.455785e+10   
Utilities                    22.075516  1.174958e+10  7.178028e+09   

                                  EBITDA               Market Cap (intraday)  \
                                    mean           std                  mean   
Sector                                                                         
Consumer Discretionary      3.787146e+09  4.843232e+09          4.170028e+10   
Consumer Staples            5.644109e+09  6.266984e+09          6.021333e+10   
Energy                      5.087549e+09  7.931613e+09          4.607476e+10   
Financials                  3.522132e+09  5.835280e+09          4.003382e+10   
Health Care                 4.600455e+09  5.371485e+09          5.316527e+10   
Industrials                 3.233267e+09  3.004607e+09          3.421159e+10   
Information Technology      6.061481e+09  1.189851e+10          9.309322e+10   
Materials                   2.723612e+09  2.442349e+09          2.713304e+10   
Real Estate                 1.408020e+09  8.561458e+08          1.983000e+10   
Telecommunication Services  3.291667e+10  2.309938e+10          1.486133e+11   
Utilities                   4.098750e+09  2.550958e+09          2.535708e+10   

                                         Forward P/E             
                                     std        mean        std  
Sector                                                           
Consumer Discretionary      8.642730e+10   15.734648  10.475492  
Consumer Staples            6.271510e+10   17.371818   5.208991  
Energy                      7.706451e+10   19.718095  13.810905  
Financials                  8.017340e+10   13.887353   4.670625  
Health Care                 6.157661e+10   17.499818   8.381433  
Industrials                 3.533104e+10   15.977143   3.987083  
Information Technology      1.724771e+11   19.033051   9.717519  
Materials                   2.942275e+10   15.747826   4.008236  
Real Estate                 1.343240e+10   46.084848  25.370267  
Telecommunication Services  1.141425e+11   11.730000   2.580930  
Utilities                   1.

In [13]:
import copy
ratio_data = copy.deepcopy(fundamental_data.iloc[:,5:])
pe_data = copy.deepcopy(ratio_data.iloc[:, [1, 5]])
ratio_data.drop(['Trailing P/E', 'Forward P/E'], axis=1, inplace=True)

In [14]:
columns = ratio_data.columns

In [15]:
for col in columns:
    ratio_data[col] /= ratio_data['Market Cap (intraday)']

In [16]:
ratio_data = pd.concat([ratio_data, pe_data], axis=1)

In [17]:
ratio_data.head()

Enterprise Value   Revenue    EBITDA  Market Cap (intraday)  Trailing P/E  \
0          1.131110  0.250812  0.070348                    1.0         26.77   
1          1.240501  0.272429  0.059280                    1.0        214.01   
2          1.287188  0.198105  0.085223                    1.0         27.21   
3          1.021207  0.378350  0.061722                    1.0         26.12   
4          1.072683  0.143324  0.045529                    1.0        179.33   

   Forward P/E  
0        18.50  
1        17.88  
2        10.28  
3        20.13  
4        21.52

In [18]:
ratio_data['Market Cap (intraday)'] = fundamental_data['Market Cap (intraday)']

In [20]:
ratio_data.index = fundamental_data['Symbol']

In [28]:
ratio_data.head()

Enterprise Value   Revenue    EBITDA  Market Cap (intraday)  \
Symbol                                                                
MMM             1.131110  0.250812  0.070348           1.262300e+11   
ABT             1.240501  0.272429  0.059280           1.005400e+11   
ABBV            1.287188  0.198105  0.085223           1.424500e+11   
ACN             1.021207  0.378350  0.061722           9.478000e+10   
ATVI            1.072683  0.143324  0.045529           4.898000e+10   

        Trailing P/E  Forward P/E  
Symbol                             
MMM            26.77        18.50  
ABT           214.01        17.88  
ABBV           27.21        10.28  
ACN            26.12        20.13  
ATVI          179.33        21.52

In [22]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

scaled_fundamental = scaler.fit_transform(ratio_data)

In [25]:
pd.DataFrame(scaled_fundamental).describe()

0           1           2           3           4           5
count  419.000000  419.000000  419.000000  419.000000  419.000000  419.000000
mean     0.330097    0.068126    0.272366    0.052583    0.045278    0.121994
std      0.083963    0.100063    0.153552    0.103886    0.083629    0.113003
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000
25%      0.279506    0.019439    0.164102    0.010694    0.015875    0.065456
50%      0.311242    0.041140    0.237696    0.020248    0.024827    0.094839
75%      0.358141    0.076817    0.343387    0.048646    0.042597    0.133241
max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000

In [26]:
from sklearn.cluster import KMeans
kmeans_transformed = KMeans(n_clusters=5).fit(scaled_fundamental)
print(kmeans_transformed.labels_)

[2 2 2 2 2 0 2 2 0 2 2 0 2 2 2 3 2 1 2 1 2 0 0 0 4 2 4 0 3 0 2 0 0 3 2 2 2
 2 0 2 2 2 2 3 1 4 2 2 0 2 0 0 2 0 2 2 0 2 2 4 0 0 2 0 2 2 0 2 2 2 2 2 2 2
 2 2 0 3 0 0 2 2 2 0 2 0 0 3 2 0 0 2 2 2 2 0 0 2 2 2 2 0 2 2 2 0 0 2 0 2 2
 2 1 2 2 3 2 2 2 3 0 3 0 1 0 2 0 0 2 2 2 0 1 0 0 2 2 0 2 2 2 3 2 0 2 1 1 1
 2 0 3 2 2 3 2 2 2 4 2 2 0 2 2 2 2 2 0 3 2 2 2 3 0 2 2 2 0 2 0 2 3 2 0 0 2
 2 3 2 1 0 2 0 2 2 2 2 2 0 2 2 2 2 2 1 2 2 2 0 0 0 2 2 2 0 2 2 0 2 2 0 2 0
 0 0 0 2 0 2 3 0 3 3 2 0 2 2 2 0 0 2 2 0 0 0 1 3 0 2 2 2 2 2 2 2 3 2 2 0 2
 0 2 2 3 4 1 0 0 2 2 2 2 2 0 2 1 0 0 0 0 2 0 3 0 2 0 0 2 2 2 0 2 2 0 0 2 2
 2 2 2 2 2 2 3 2 2 0 2 2 3 2 0 2 2 2 0 0 2 0 2 2 0 0 3 2 2 2 2 2 0 2 2 2 2
 2 2 0 1 1 0 0 0 2 2 2 1 0 0 0 2 2 2 0 2 2 2 0 2 2 2 0 2 2 2 2 2 2 0 2 2 2
 0 2 2 2 0 1 2 2 3 2 0 0 2 0 0 2 0 2 2 2 2 3 2 3 2 1 2 0 0 2 2 1 0 2 0 0 2
 3 0 2 0 2 0 3 2 2 2 0 2]


In [27]:
len(kmeans_transformed.labels_)

419

In [34]:
ratio_csv = pd.read_csv('./fundamental_data/ratio_data.csv')

In [37]:
ratio_csv.head()

Symbol  Enterprise Value   Revenue    EBITDA  Market Cap (intraday)  \
0    MMM          1.131110  0.250812  0.070348           1.262300e+11   
1    ABT          1.240501  0.272429  0.059280           1.005400e+11   
2   ABBV          1.287188  0.198105  0.085223           1.424500e+11   
3    ACN          1.021207  0.378350  0.061722           9.478000e+10   
4   ATVI          1.072683  0.143324  0.045529           4.898000e+10   

   Trailing P/E  Forward P/E  
0         26.77        18.50  
1        214.01        17.88  
2         27.21        10.28  
3         26.12        20.13  
4        179.33        21.52

In [41]:
ratio_csv.index

RangeIndex(start=0, stop=419, step=1)

In [40]:
fundamental_data.index

RangeIndex(start=0, stop=419, step=1)

In [47]:
ratio_csv['Sector'] = fundamental_data['Sector']

In [48]:
ratio_csv.head()

Symbol  Enterprise Value   Revenue    EBITDA  Market Cap (intraday)  \
0    MMM          1.131110  0.250812  0.070348           1.262300e+11   
1    ABT          1.240501  0.272429  0.059280           1.005400e+11   
2   ABBV          1.287188  0.198105  0.085223           1.424500e+11   
3    ACN          1.021207  0.378350  0.061722           9.478000e+10   
4   ATVI          1.072683  0.143324  0.045529           4.898000e+10   

   Trailing P/E  Forward P/E                  Sector  
0         26.77        18.50             Industrials  
1        214.01        17.88             Health Care  
2         27.21        10.28             Health Care  
3         26.12        20.13  Information Technology  
4        179.33        21.52  Information Technology

In [50]:
sectors = list(set(fundamental_data['Sector']))

sectors_df = {}
for sector in sectors:
    this_sector_df = copy.deepcopy(ratio_csv[ratio_csv['Sector'] == sector])
    sectors_df[sector] = this_sector_df

In [60]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

for sector_key in sectors_df:
    df = sectors_df[sector_key].drop(['Sector', 'Symbol'], axis=1)
    df = scaler.fit_transform(df)
    n_clusters = min(df.shape[0], 5)
    kmeans_transformed = KMeans(n_clusters=n_clusters).fit(df)
    print(kmeans_transformed.labels_)
    

[0 1 2]
[2 1 1 1 0 0 1 3 0 1 0 2 0 0 2 0 2 4 1 1 0 1 0 0 2 1 2 1 0 2 2 2 1 2]
[2 3 0 4 1 1 3 1 3 4 1 2 3 1 1 2 1 3 0 2 3]
[1 1 1 1 1 2 3 1 0 1 3 0 1 0 0 1 0 1 0 3 0 1 1 1 1 2 2 0 0 1 1 0 0 0 1 0 2
 3 4 1 0 1 1 0 1 4 0 0 1 1 1 0 1 0 1 1 2 2 1]
[0 3 0 2 1 0 2 2 0 2 2 0 2 0 0 2 0 0 0 2 4 2 0 0 1 2 2 0 0 2 1 2 0 0 0 0 1
 0 0 2 0 0 2 0 1 2 0 2 2 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 2 0 1 0 0 0]
[1 0 2 0 2 2 4 2 0 2 2 0 2 2 0 2 2 0 0 0 0 3 2 0 0 2 1 1 1 0 0 1 0]
[4 2 3 1 3 1 1 4 2 0 1 2 2 0 3 2 2 1 1 1 1 2 2 1 2 1 1 4 2 1 1 2 2 1 0 2 1
 4 2 0 2 1 2 2 2 2 1 1 2 1 1 1 2 0 2 4 3 4 0 4 1 1 1]
[4 1 4 4 4 2 0 1 4 4 4 4 4 4 0 4 4 4 4 4 4 3 2 3 1 3 4 4 4 2 2 2 4 1 4 0 4
 1 2 3 4 4 1 4 4 2 4 4 1 3 2 2 2 3 2]
[1 1 4 1 1 2 3 3 1 3 1 1 1 1 0 0 1 0 0 4 1 1 1 1 1 3 1 0 4 0 0 0 1]
[0 2 2 0 2 2 2 4 2 4 2 3 2 3 0 1 3 2 4 0 1 4 0 2]
[1 4 3 2 3 0 2 1 3 2 2 1 2 1 1 2 3 3 1 3 3 1 2]


In [56]:
# for sector_key in sectors_df:
#     sectors_df[sector_key].to_csv('./fundamental_data/{}_ratio'.format(sector_key))